export default {
  data: [
    { id: 1, name: 'E-commerce', emoji: '🛒' },
    { id: 2, name: 'Healthcare', emoji: '🏥' },
    { id: 3, name: 'Education', emoji: '📚' },
    { id: 4, name: 'Finance', emoji: '💰' },
    { id: 5, name: 'Social Media', emoji: '📱' },
    { id: 6, name: 'Travel and Hospitality', emoji: '✈️' },
    { id: 7, name: 'Entertainment', emoji: '🎥' },
    { id: 8, name: 'News and Media', emoji: '📰' },
    { id: 9, name: 'Real Estate', emoji: '🏠' },
    { id: 10, name: 'Food and Dining', emoji: '🍔' },
    { id: 11, name: 'Transportation', emoji: '🚗' },
    { id: 12, name: 'Fitness and Wellness', emoji: '💪' },
    { id: 13, name: 'Government and Civic', emoji: '🏛️' },
    { id: 14, name: 'Nonprofits and Charities', emoji: '🤝' },
    { id: 15, name: 'Gaming', emoji: '🎮' },
    { id: 16, name: 'Automotive', emoji: '🚗' },
    { id: 17, name: 'Industrial and Manufacturing', emoji: '🏭' },
    { id: 18, name: 'Agriculture', emoji: '🌾' },
    { id: 19, name: 'Aerospace', emoji: '🚀' },
    { id: 20, name: 'Fashion', emoji: '👗' },
    { id: 21, name: 'Environmental Sustainability', emoji: '🌿' },
    { id: 22, name: 'Legal and Compliance', emoji: '⚖️' },
    { id: 23, name: 'HR and Recruitment', emoji: '👥' },
    { id: 24, name: 'Machine Learning and Data Analytics', emoji: '🤖' },
    { id: 25, name: 'IoT (Internet of Things)', emoji: '📡' },
    { id: 26, name: 'Weather and Forecasting', emoji: '🌦️' },
    { id: 27, name: 'Music and Audio', emoji: '🎵' },
    { id: 28, name: 'Interior Design and Home Decor', emoji: '🏡' },
    { id: 29, name: 'Event Management', emoji: '🎉' },
    { id: 30, name: 'Legal and Justice', emoji: '⚖️' },
    { id: 31, name: 'Virtual Reality (VR) and Augmented Reality (AR)', emoji: '🕶️' },
    { id: 32, name: 'Cryptocurrency and Blockchain', emoji: '💱' },
    { id: 33, name: 'Art and Creativity', emoji: '🎨' },
    { id: 34, name: 'Science and Research', emoji: '🔬' },
    { id: 35, name: 'Space Exploration', emoji: '🚀' },
    { id: 36, name: "Children's Apps", emoji: '👶' },
    { id: 37, name: 'Accessibility Solutions', emoji: '♿' },
    { id: 38, name: 'Smart Cities', emoji: '🌆' },
    { id: 39, name: 'Pet Care and Veterinary', emoji: '🐾' },
    { id: 40, name: 'Language Learning', emoji: '🗣️' },
    { id: 41, name: 'Photography and Image Editing', emoji: '📷' },
    { id: 42, name: 'Charitable Giving', emoji: '🤲' },
    { id: 43, name: 'Renewable Energy', emoji: '♻️' },
    { id: 44, name: 'Mental Health and Well-being', emoji: '🧠' },
    { id: 45, name: 'Supply Chain Management', emoji: '📦' },
    { id: 46, name: 'Customer Support and Help Centers', emoji: '📞' },
    { id: 47, name: 'Home Automation and IoT', emoji: '🏡' },
    { id: 48, name: 'Biotechnology and Life Sciences', emoji: '🧬' },
    { id: 49, name: 'Renewable Energy and Sustainability Monitoring', emoji: '♻️' },
    { id: 50, name: 'Blockchain and NFT Marketplaces', emoji: '💱' },
    { id: 51, name: 'Space Tourism', emoji: '🚀' },
    { id: 52, name: 'Agricultural Technology (AgTech)', emoji: '🌾' },
    { id: 53, name: 'Blockchain and Cryptocurrency Gaming', emoji: '🎮' }
  ]
}
